### ISSUE TITLE
Handle license shortcode on work without license

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/wp-plugin-creativecommons#31]
Currently we get a malformed license block:

![image](https://cloud.githubusercontent.com/assets/21746/21871814/800897ec-d819-11e6-995e-3e9b6d7ea407.png)

It's not a showstopper but should be cleaned up.

Do *not* implement an all rights reserved path to handle this.

**Comment by possumbilities** [comment]
Since the implementation of the CC Licenses as Gutenberg Blocks, editor shortcodes are no longer used to include licenses within content. 

Additionally, the Classic Editor plugin will have official support ended as of Dec 31, 2022, and is no longer part of core, which means any legacy usage is both no longer a part of core WordPress and also about to lose official support.
