### ISSUE TITLE
Other Attribution Text not used on home page

### ISSUE THREAD

**Issue by cogdog** [creativecommons/wp-plugin-creativecommons#50]
Experimenting with the other attribution text:

![other text](https://cloud.githubusercontent.com/assets/463038/22121619/08122792-de42-11e6-9748-16c06a757e87.jpg)

On the home and archive page it's not used:

![no noun](https://cloud.githubusercontent.com/assets/463038/22121644/1781ad74-de42-11e6-940d-87c7f528f6e3.jpg)

And if there is no URL, it is missing before/after spaces on single posts

![other attr needs text](https://cloud.githubusercontent.com/assets/463038/22121680/31ed1bbc-de42-11e6-9db5-46b5159243a3.jpg)

**Comment by simpson13579** [comment]
qx1232

**Comment by ahmadbilaldev** [comment]
Settings have been re-designed. The given error has also been fixed in [Show additional attribution text on all pages](https://github.com/creativecommons/wp-plugin-creativecommons/commit/151c1e7b1909a072057f165ead85e880fe31a072).

![cc-settings](https://user-images.githubusercontent.com/19692245/63625727-e893e780-c619-11e9-92da-81ddfd98b5ba.png)
*Settings*
